global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "backend"
    static_configs:
      - targets: ["backend:8080"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  - job_name: "nginx"
    static_configs:
      - targets: ["nginx:80"]
    metrics_path: "/metrics"
    scrape_interval: 10s

  - job_name: "postgres"
    static_configs:
      - targets: ["db:5432"]
    scrape_interval: 10s

  - job_name: "docker"
    static_configs:
      - targets: ["host.docker.internal:9323"]
    scrape_interval: 10s
